name: codecrafters-redis
version: 0.1.0.0
license: BSD3
language: GHC2021
default-extensions:
  - MultiWayIf
  - RecordWildCards
  - OverloadedRecordDot

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
  dependencies:
    - base >= 4.18 && < 5
    - bytestring
    - containers
    - fast-logger
    - mtl
    - network-simple
    - parsec
    - stm
    - time
    - random

executables:
  codecrafters-redis-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.18 && < 5
      - codecrafters-redis
      - mtl
      - network-simple
      - fast-logger
      - optparse-applicative

tests:
  codecrafters-redis-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - base >= 4.18 && < 5
      - codecrafters-redis
      - time
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - hedgehog
